# This file is used by the Makefile.
# You should never need to modify it.
version: "3"
services:

  db-task:
    image: postgres:10-alpine
    networks:
      - lisk
    environment:
      - PGUSER=${ENV_LISK_DB_USER}
      - PGPASSWORD=${ENV_LISK_DB_PASSWORD}
      - PGDATABASE=${ENV_LISK_DB_DATABASE}
      - PGHOST=db
    command: /bin/true
