# Override file to add caching (redis) to the base configuration
# E.g.: docker-compose -f docker-compose.yml -f docker-compose.redis.yml -f docker-compose.override.yml up -d
version: "3"
services:

  lisk:
    depends_on:
      - redis
    environment:
      - LISK_CACHE_ENABLED=true
      - LISK_REDIS_HOST=redis
      - LISK_REDIS_PORT=6379

  redis:
    image: redis:alpine
    networks:
      - lisk
    restart: on-failure
    command: --maxclients 500 --tcp-backlog 128 --maxmemory-policy allkeys-lru --save ""
