codecov:
  max_report_age: 30
  notify:
    wait_for_ci: false
github_checks:
  annotations: false
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
comment:
  layout: "reach, diff, flags, files"
  behavior: default
