'use strict';

var set = require('lodash').set;

var UPDATES = {
	INSERT: 0,
	REMOVE: 1
};

var ON_CONNECTIONS_TABLE = {
	NONCE: {
		PRESENT: true,
		NOT_PRESENT: false
	},
	CONNECTION_ID: {
		PRESENT: true,
		NOT_PRESENT: false
	}
};

var ON_MASTER = {
	PRESENT: true,
	NOT_PRESENT: false
};

/**
 * @param {function} allow
 * @param {function} block
 * @param {function} panic
 * @constructor
 */
function Rules (allow, block, panic) {
	this.rules = {};
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.PRESENT]].join('.'), panic);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.PRESENT]].join('.'), block);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.INSERT], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.NOT_PRESENT]].join('.'), allow);

	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.PRESENT]].join('.'), block);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.PRESENT],     [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.PRESENT],     [ON_MASTER.NOT_PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.PRESENT]].join('.'), allow);
	set(this.rules, [[UPDATES.REMOVE], [ON_CONNECTIONS_TABLE.NONCE.NOT_PRESENT], [ON_CONNECTIONS_TABLE.CONNECTION_ID.NOT_PRESENT], [ON_MASTER.NOT_PRESENT]].join('.'), block);
}

Rules.UPDATES = UPDATES;
Rules.ON_CONNECTIONS_TABLE = ON_CONNECTIONS_TABLE;
Rules.ON_MASTER = ON_MASTER;

module.exports = Rules;
