/*
 * Copyright © 2018 Lisk Foundation
 *
 * See the LICENSE file at the top-level directory of this distribution
 * for licensing information.
 *
 * Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
 * no part of this software, including this file, may be copied, modified,
 * propagated, or distributed except according to the terms contained in the
 * LICENSE file.
 *
 * Removal or modification of this copyright notice is prohibited.
 */


/*
  DESCRIPTION: Mem_accounts doesn't have unique row identification in v2.0

  PARAMETERS: None
*/

ALTER TABLE "mem_accounts" ADD COLUMN IF NOT EXISTS "rowId" INT GENERATED BY DEFAULT AS IDENTITY
   (START WITH 1 INCREMENT BY 1);