---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-lisk-core"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-lisk-core"
    helm.sh/chart: {{ include "lisk-core.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: lisk-core-http
      port: {{ .Values.lisk.httpPort }}
      targetPort: lisk-core-http
      protocol: TCP
    - name: lisk-core-ws
      port: {{ .Values.lisk.wsPort }}
      targetPort: lisk-core-ws
      protocol: TCP
  selector:
    app.kubernetes.io/name: "{{ include "lisk-core.name" . }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
