---
replicaCount: 1

# This is for database (postgresql) container and can be expanded
persistence:
  enable: true
  storage: 10Gi

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

lisk:
  loglevel: info
  network: testnet
  coldstart: true
  wsPort: 7001
  httpPort: 7000
  api:
    public: true
  database:
    user: lisk
    password: lisk
  image:
    repository: lisk/core
    tag: 1.6.0-alpha.5
    pullPolicy: IfNotPresent

postgresql:
  image:
    repository: postgres
    tag: 10-alpine
    pullPolicy: IfNotPresent
