@Library('lisk-jenkins') _
pipeline {
	agent { node { label 'lisk-framework' } }

	stages {
		stage('Build') {
			steps {
				nvm(getNodejsVersion()) {
					sh '''
						echo 'Deprecated'
					'''
				}
			}
		}
	}
	post {
		cleanup {
			cleanWs()
		}
	}
}
// vim: filetype=groovy
