/*
 * Copyright © 2021 Lisk Foundation
 *
 * See the LICENSE file at the top-level directory of this distribution
 * for licensing information.
 *
 * Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
 * no part of this software, including this file, may be copied, modified,
 * propagated, or distributed except according to the terms contained in the
 * LICENSE file.
 *
 * Removal or modification of this copyright notice is prohibited.
 */
import * as React from 'react';
import { TableBody, TableHeader } from '../Table';
import Grid from '../Grid';
import CopiableText from '../CopiableText';
import { Widget, WidgetHeader, WidgetBody } from '../widget';
import Text from '../Text';
import styles from './Widgets.module.scss';

interface WidgetProps {
	scrollbar?: boolean;
	blocks: Record<string, string>[];
	widgetTitle: string;
}

const BlockWidget: React.FC<WidgetProps> = props => {
	if (props.blocks.length === 0) return null;

	const scrollbar = props.scrollbar ?? true;
	const { blocks, widgetTitle } = props;

	return (
		<Widget>
			<WidgetHeader>
				<Text type={'h2'}>{widgetTitle}</Text>
			</WidgetHeader>
			<WidgetBody>
				<div className={styles['table-container']}>
					<TableHeader>
						<Grid rowNoWrap>
							<Grid xs={5}>
								<Text type={'th'}>Id</Text>
							</Grid>
							<Grid xs={4}>
								<Text type={'th'}>Generated by</Text>
							</Grid>
							<Grid xs={2}>
								<Text type={'th'}>Height</Text>
							</Grid>
							<Grid xs={1}>
								<Text type={'th'}>Txs</Text>
							</Grid>
						</Grid>
					</TableHeader>
				</div>
				<TableBody size={'m'} scrollbar={scrollbar}>
					{blocks.map((block, index) => (
						<Grid rowNoWrap key={index}>
							<Grid xs={5}>
								<CopiableText text={block.id} type={'p'}>
									{block.id}
								</CopiableText>
							</Grid>
							<Grid xs={4}>
								<CopiableText text={block.generatedBy} type={'p'}>
									{block.generatedBy}
								</CopiableText>
							</Grid>
							<Grid xs={2}>
								<Text type={'p'} key={block.height}>
									{block.height}
								</Text>
							</Grid>
							<Grid xs={1}>
								<Text type={'p'} key={block.txs}>
									{block.txs}
								</Text>
							</Grid>
						</Grid>
					))}
				</TableBody>
			</WidgetBody>
		</Widget>
	);
};

export default BlockWidget;
