/*
 * Copyright © 2021 Lisk Foundation
 *
 * See the LICENSE file at the top-level directory of this distribution
 * for licensing information.
 *
 * Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
 * no part of this software, including this file, may be copied, modified,
 * propagated, or distributed except according to the terms contained in the
 * LICENSE file.
 *
 * Removal or modification of this copyright notice is prohibited.
 */
import * as React from 'react';
import { TableBody, TableHeader, Table } from '../Table';
import CopiableText from '../CopiableText';
import { Widget, WidgetHeader, WidgetBody } from '../widget';
import Text from '../Text';

interface WidgetProps {
	blocks: Record<string, string>[];
	title: string;
}

const BlockWidget: React.FC<WidgetProps> = props => {
	const { blocks, title } = props;

	return (
		<Widget>
			<WidgetHeader>
				<Text type={'h2'}>{title}</Text>
			</WidgetHeader>
			<WidgetBody>
				<Table>
					<TableHeader sticky>
						<tr>
							<th style={{ width: 'calc(60% - 110px)' }}>
								<Text>Id</Text>
							</th>
							<th style={{ width: 'calc(40% - 110px)' }}>
								<Text>Generated by</Text>
							</th>
							<th style={{ width: '70px' }}>
								<Text>Height</Text>
							</th>
							<th style={{ width: '40px' }}>
								<Text>Txs</Text>
							</th>
						</tr>
					</TableHeader>
					<TableBody>
						{blocks.map((block, index) => (
							<tr key={index}>
								<td>
									<CopiableText text={block.id}>{block.id}</CopiableText>
								</td>
								<td>
									<CopiableText text={block.generatedBy}>{block.generatedBy}</CopiableText>
								</td>
								<td>
									<Text key={block.height}>{block.height}</Text>
								</td>
								<td>
									<Text key={block.txs}>{block.txs}</Text>
								</td>
							</tr>
						))}
					</TableBody>
				</Table>
			</WidgetBody>
		</Widget>
	);
};

export default BlockWidget;
