export const TRANSACTION_TYPE_TRANSFER = 0;
export const TRANSACTION_TYPE_SECOND_SIGNATURE = 1;
export const TRANSACTION_TYPE_DELEGATE = 2;
export const TRANSACTION_TYPE_VOTE = 3;
export const TRANSACTION_TYPE_MULTISIGNATURE = 4;
export const TRANSACTION_TYPE_DAPP = 5;
export const TRANSACTION_TYPE_IN_TRANSFER = 6;
export const TRANSACTION_TYPE_OUT_TRANSFER = 7;
