name: "Branch"

on:
  push:
    branches: [ "development", feature/*, hotfix/*, main, release/* ]

jobs:
  code-cov-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        uses: ./.github/actions/prepare-install
      - name: Build
        uses: ./.github/actions/prepare-build
        with:
          cache-key: ${{ github.ref }}
      - run: yarn test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-final.json
          name: codecov-umbrella
      - run: npm config set //npm.lisk.com/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: npx lerna publish --canary --preid canary --registry https://npm.lisk.com --yes
